apiVersion: v1
kind: Service
metadata:
  name: genai-service
  namespace: genai-platform
spec:
  type: LoadBalancer
  selector:
    app: genai-inference
  ports:
    - port: 80
      targetPort: 8000
